before:
  hooks:
    - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

  binary: '{{ .ProjectName }}'
  main: cmd/shuffledns/main.go

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256

snapcrafts:
  - id: shuffledns
    replacements:
      darwin: macOS
    name: proxify
    publish: false
    summary: shuffleDNS is a wrapper around massdns written in go.
    description: |
      shuffleDNS is a wrapper around massdns written in go that allows you to enumerate valid subdomains using active bruteforce as well as resolve subdomains with wildcard handling and easy input-output support.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      shuffledns:
        command: shuffledns
        plugs:
          - home
          - network
          - removable-media
          - dot-shuffledns
    plugs:
      dot-shuffledns:
        interface: personal-files
        write:
          - $HOME/.config/shuffledns